---

services:
  temporal-database:
    image: postgres:16.3-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-temporal-database
    restart: on-failure
    networks:
      - default
      - shared
    ports:
      - '${TEMPORAL_DB_FORWARD_PORT:-5446}:5432'
    environment:
      POSTGRES_USER: ${TEMPORAL_DB_USERNAME}
      POSTGRES_PASSWORD: ${TEMPORAL_DB_PASSWORD}
      POSTGRES_DB: ${TEMPORAL_DB_DATABASE}
    volumes:
      - temporal-database-data:/var/lib/postgresql/data:cached

  temporal:
    image: temporalio/auto-setup:1.24.2
    container_name: ${COMPOSE_PROJECT_NAME}-temporal
    restart: on-failure
    networks:
      - default
      - shared
    depends_on:
      - temporal-database
    ports:
      - '${TEMPORAL_FORWARD_PORT:-7233}:7233'
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${TEMPORAL_DB_USERNAME}
      - POSTGRES_PWD=${TEMPORAL_DB_PASSWORD}
      - POSTGRES_SEEDS=temporal-database
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./docker/temporal:/etc/temporal/config/dynamicconfig

  temporal-ui:
    image: temporalio/ui:2.29.2
    container_name: ${COMPOSE_PROJECT_NAME}-temporal-ui
    restart: on-failure
    networks:
      - default
      - shared
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=https://temporal.${COMPOSE_PROJECT_NAME}.docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.temporal-ui-${COMPOSE_PROJECT_NAME}.rule=Host(`temporal.${COMPOSE_PROJECT_NAME}.docker`)
      - traefik.http.routers.temporal-ui-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.temporal-ui-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.services.temporal-ui-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080
      - traefik.http.services.temporal-ui-${COMPOSE_PROJECT_NAME}.loadbalancer.server.scheme=http

volumes:
  temporal-database-data:
    name: ${COMPOSE_PROJECT_NAME}-temporal-database-data

networks:
  shared:
    external: true
    name: network.${SHARED_SERVICES_NAMESPACE}
  default:
    name: project.${COMPOSE_PROJECT_NAME}
