---

# https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml

version: '3'

rpc:
  listen: 'tcp://127.0.0.1:6001'

metrics:
  address: '127.0.0.1:2112'

server:
  command: 'php app.php'
  relay: pipes

logs:
  level: debug

http:
  address: '0.0.0.0:8668'
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    debug: false
    num_workers: 2
    supervisor:
      max_worker_memory: 100

kv:
  local:
    driver: memory
    config:
      interval: 60

temporal:
  address: 'temporal:7233'
  activities:
    debug: true
    num_workers: 4

jobs:
  pool:
    num_workers: 1
    max_worker_memory: 100
  consume: []
